# Generated by Django 4.2.1 on 2023-06-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_item',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
